INSERT INTO base (id,
                  created_date,
                  last_modified_date,
                  name,
                  score,
                  image_url,
                  is_active
) VALUES (10001,
          '08-16-2020 01:00:00',
          '08-16-2020 01:00:00',
          'base1',
          0.0,
          'https://images.unsplash.com/photo-1597476934600-ef660b4ce617?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80',
          true),
         (10002,
          '08-17-2020 01:00:00',
          '08-17-2020 01:00:00',
          'base2',
          0.0,
          'https://images.unsplash.com/photo-1597415885008-d7929349a704?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
          true),
         (10003,
          '08-17-2020 01:00:00',
          '08-17-2020 01:00:00',
          'base3',
          0.0,
          'https://images.unsplash.com/photo-1597055181449-b3f17e2ada63?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80',
          true);

INSERT INTO base_member (id,
                         base_id,
                         member_id,
                         role)
VALUES (2000,
        (SELECT id from base where name='base1'),
        (SELECT id from jhi_user where login='arcq'),
        'ADMIN'),
        (2001,
        (SELECT id from base where name='base1'),
        (SELECT id from jhi_user where login='sita'),
        'MEMBER'),
       (2002,
        (SELECT id from base where name='base1'),
        (SELECT id from jhi_user where login='d0nkers'),
        'MEMBER');

INSERT INTO base_member (id,
                         base_id,
                         member_id,
                         role)
VALUES (2003,
        (SELECT id from base where name='base2'),
        (SELECT id from jhi_user where login='arcq'),
        'MEMBER'),
       (2004,
        (SELECT id from base where name='base2'),
        (SELECT id from jhi_user where login='sita'),
        'ADMIN');


insert into base_member (id,
                         base_id,
                         member_id,
                         role)
VALUES (2005,
        (SELECT id from base where name='base3'),
        (SELECT id from jhi_user where login='d0nkers'),
        'MEMBER'),
       (2006,
        (SELECT id from base where name='base3'),
        (SELECT id from jhi_user where login='arcq'),
        'ADMIN');
