version: '2'
services:
  touchbase-app:
    image: touchbase
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - MICRONAUT_ENVIRONMENTS=prod
      - JDBC_URL=jdbc:postgresql://touchbase-postgresql:5432/touchbase
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  touchbase-postgresql:
    extends:
      file: postgresql.yml
      service: touchbase-postgresql
